### ISSUE TITLE
Missing system exception

### ISSUE THREAD

**Issue by kolba** [stringandstickytape/RegulatedNoise#4]
After a quick glimpse at the code it seems that its due to some misspelled system name in the csv im trying to load? Surely can be handled nicer :)

```
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at RegulatedNoise.Form1.DistanceInLightYears(String remoteSystemName) in d:\git\RN3\RegulatedNoise\RegulatedNoise\Form1.cs:line 861
   at RegulatedNoise.Form1.<SetupGui>b__1a(KeyValuePair`2 x) in d:\git\RN3\RegulatedNoise\RegulatedNoise\Form1.cs:line 939
   at System.Linq.EnumerableSorter`2.ComputeKeys(TElement[] elements, Int32 count)
   at System.Linq.EnumerableSorter`1.Sort(TElement[] elements, Int32 count)
   at System.Linq.OrderedEnumerable`1.<GetEnumerator>d__0.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at RegulatedNoise.Form1.SetupGui() in d:\git\RN3\RegulatedNoise\RegulatedNoise\Form1.cs:line 939
   at RegulatedNoise.Form1.bOpen_Click(Object sender, EventArgs e) in d:\git\RN3\RegulatedNoise\RegulatedNoise\Form1.cs:line 731
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

**Comment by stringandstickytape** [comment]
Good catch.  I've just pushed a fix for this, it will be in the next version.
